apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: airflow

resources:
  - database/postgres-secret.yaml
  - database/postgres-deployment.yaml
  - database/postgres-service.yaml

  - airflow/airflow-dags-configmap.yaml
  - airflow/airflow-db-init-job.yaml
  - airflow/deployment.yaml
  - airflow/scheduler-deployment.yaml
  - airflow/service.yaml

  - platform/networkpolicy.yaml
  - platform/poddisruptionbudget.yaml

configMapGenerator:
  - name: airflow-config
    files:
      - airflow/airflow.cfg

  - name: airflow-env
    envs:
      - airflow/env.properties

generatorOptions:
  disableNameSuffixHash: true
