apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: airflow-allow-web
  namespace: airflow
spec:
  podSelector:
    matchLabels:
      app: airflow-webserver
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 8080
