apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: airflow
data:
  airflow.cfg: |
    [core]
    dags_folder = /opt/airflow/dags
    executor = LocalExecutor
    load_examples = False
