apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-dags
  namespace: airflow
data:

  test_dag.py: |
    from airflow import DAG
    from airflow.operators.bash import BashOperator
    from datetime import datetime

    with DAG(
        dag_id="test_dag",
        start_date=datetime(2024, 1, 1),
        schedule_interval="@daily",
        catchup=False
    ) as dag:
        BashOperator(
            task_id="hello",
            bash_command="echo Hello Airflow"
        )

  hello_world.py: |
    from airflow import DAG
    from airflow.operators.bash import BashOperator
    from datetime import datetime

    with DAG(
        dag_id="hello_world",
        start_date=datetime(2024, 1, 1),
        schedule_interval=None,
        catchup=False
    ) as dag:
        BashOperator(
            task_id="say_hello",
            bash_command="echo Hello World"
        )

  two_tasks.py: |
    from airflow import DAG
    from airflow.operators.bash import BashOperator
    from datetime import datetime

    with DAG(
        dag_id="two_tasks_example",
        start_date=datetime(2024, 1, 1),
        schedule_interval="@hourly",
        catchup=False
    ) as dag:

        task_1 = BashOperator(
            task_id="task_1",
            bash_command="echo Task 1 running"
        )

        task_2 = BashOperator(
            task_id="task_2",
            bash_command="echo Task 2 running"
        )

        task_1 >> task_2

  python_task.py: |
    from airflow import DAG
    from airflow.operators.python import PythonOperator
    from datetime import datetime

    def print_message():
        print("This is a Python task")

    with DAG(
        dag_id="python_task_example",
        start_date=datetime(2024, 1, 1),
        schedule_interval="@daily",
        catchup=False
    ) as dag:

        PythonOperator(
            task_id="print_message",
            python_callable=print_message
        )
