apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:

      # 🔹 Airflow container (scheduler + webserver)
      - name: airflow
        image: sivaji9412/airflow-local:2.0
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: airflow-config
        - secretRef:
            name: airflow-secrets
        volumeMounts:
        - name: airflow-data
          mountPath: /opt/airflow/dags
          subPath: dags
        - name: airflow-data
          mountPath: /opt/airflow/logs
          subPath: logs
        command: ["/bin/bash", "-c"]
        args:
          - |
            echo "Starting Airflow DB init"
            airflow db init || true

            echo "Starting Airflow Scheduler"
            airflow scheduler &

            echo "Starting Airflow Webserver"
            exec airflow webserver

      # 🔹 StatsD sidecar container
      - name: statsd
        image: prom/statsd-exporter:v0.28.0
        args:
          - "--statsd.listen-udp=:8125"
        ports:
        - containerPort: 8125
          protocol: UDP
        - containerPort: 9102

      volumes:
      - name: airflow-data
        persistentVolumeClaim:
          claimName: airflow-pvc