apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  namespace: airflow
type: Opaque
stringData:
  # DB
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow

  # Admin user (best practice)
  AIRFLOW_ADMIN_USERNAME: admin
  AIRFLOW_ADMIN_PASSWORD: admin
  AIRFLOW_ADMIN_FIRSTNAME: Admin
  AIRFLOW_ADMIN_LASTNAME: User
  AIRFLOW_ADMIN_EMAIL: jsivajigoud9412@gmail.com