apiVersion: v1
kind: Service
metadata:
  name: statsd-exporter
  namespace: airflow
spec:
  selector:
    app: statsd-exporter
  ports:
    - name: statsd
      port: 9125
      targetPort: 9125
      protocol: UDP
    - name: metrics
      port: 9102
      targetPort: 9102
      protocol: TCP
